### ISSUE TITLE
Store user result for each question in the db as an array 

### ISSUE THREAD

**Issue by Bilalm354** [haffi96/quiz-app#47]
@Bilalm354 wdym by storing in an array?

Update: Idea below is probably too much. We could just have a `previous_attempt_result` column on a question for the user

Idea:
  - Could have an attempts counter on each question
  - A submissions table which stores the submitted result for each question for each user (will be a big table but this is why postgres is good, fetching a user result even if its a big table would be quick)

So a `submissions` table could be like this:

| id | user_id | question_id | result |
| - | - | - | - |
| 1 | 1 | 1 | incorrect |

**Comment by haffi96** [comment]
Potentially doing it differently now? So close this if you want @Bilalm354
