### ISSUE TITLE
Investigation: Figure out how to make questions sets work

### ISSUE THREAD

**Issue by haffi96** [haffi96/quiz-app#58]
There is alot of tickets on question sets related stuff and how the ux will be depends on how question sets work, so this is to make a plan and either clean up the tickets or figure out in which order to do them in

Things that need to be figure out:
- What will the information in question_sets table be?
- How do questions - question_sets link?
- When a user selects a question_set, what happens? 

Options: Do we fetch a pre-determined list of questions which are related to that question set and queue them in state, so when the clicks next or prev, it will only go to the right questions

**Comment by haffi96** [comment]
https://excalidraw.com/#room=8d31407f598366e0c2ec,lGLPoum4nFsmziTFv-w-Fw

![image](https://user-images.githubusercontent.com/53666594/214389457-27d71244-8606-4a13-9950-6e4c6a75a532.png)

**Comment by Bilalm354** [comment]
Do we fetch a pre-determined list of questions which are related to that question set and queue them in state, so when the clicks next or prev, it will only go to the right questions

Maybe create functions getNextQuestionInSet and getPreviousQuestionInSet ? 

Plus have the question sidebar only show questions from the question set
